export const SITE = {
  website: "https://blog.lg37.com/",
  author: "liuenyin",
  profile: "https://github.com/liuenyin",
  desc: "liuenyin的个人博客 - 算法·竞赛·随笔",
  title: "liuenyin's blog",
  ogImage: "og-image.png",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/liuenyin/lg37blog/edit/master/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
